/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 18 06:18:11 GMT 2017
 */

package edu.osu.cs362;

import org.junit.Test;
import static org.junit.Assert.*;
import edu.osu.cs362.Unit;
import java.util.NoSuchElementException;
import org.junit.runner.RunWith;


public class Unit_ESTest extends Unit_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Unit unit0 = new Unit();
      unit0.SetAbility("_^s3=K0W%rv", 1.0, 2708);
      unit0.GetTreasure();
      assertEquals(2709, unit0.GetLevel());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Unit unit0 = new Unit();
      unit0.SetAbility("", 1140.442090625, (-1));
      unit0.Attacking();
      assertEquals(0, unit0.GetLevel());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Unit unit0 = new Unit();
      unit0.SetAbility("jV a(*", 1.0, (-393));
      int int0 = unit0.GetLevel();
      assertEquals((-393), int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Unit unit0 = new Unit();
      int int0 = unit0.GetLevel();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Unit unit0 = new Unit();
      unit0.SetAbility("1+Y8/E", 1, 10);
      // Undeclared exception!
      try { 
        unit0.GetTreasure();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // Cannot level up
         //
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Unit unit0 = new Unit();
      // Undeclared exception!
      try { 
        unit0.Attacking();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // Cannot defeaat the monster
         //
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Unit unit0 = new Unit();
      unit0.SetAbility("", 1000.0, 0);
      unit0.Attacking();
      int int0 = unit0.GetLevel();
      assertEquals(1, int0);
  }
}
