/*
 * This file was automatically generated by EvoSuite
 * Thu May 11 07:51:41 GMT 2017
 */

package edu.osu.cs362;

import org.junit.Test;
import static org.junit.Assert.*;
import edu.osu.cs362.Appt;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class Appt_ESTest extends Appt_ESTest_scaffolding {

  @Test
  public void test00()  throws Throwable  {
      Appt appt0 = new Appt(11, 11, 11, 11, 11, "E", "E");
      assertEquals("E", appt0.getDescription());
      
      appt0.setDescription((String) null);
      assertEquals(11, appt0.getStartHour());
  }

  @Test
  public void test01()  throws Throwable  {
      Appt appt0 = new Appt(0, 0, 0, 0, 0, " x/EqG8=&q-", " x/EqG8=&q-");
      appt0.setTitle(" x/EqG8=&q-");
      assertEquals(" x/EqG8=&q-", appt0.getDescription());
      assertEquals(0, appt0.getStartHour());
      assertEquals(0, appt0.getStartMonth());
      assertEquals(0, appt0.getStartMinute());
      assertEquals(" x/EqG8=&q-", appt0.getTitle());
      assertEquals(0, appt0.getStartDay());
      assertEquals(0, appt0.getStartYear());
      assertFalse(appt0.getValid());
  }

  @Test
  public void test02()  throws Throwable  {
      Appt appt0 = new Appt(1540, 1540, 1540, 1540, 1540, "tsT8J2xNs", "");
      assertEquals("", appt0.getDescription());
      
      appt0.setDescription("");
      assertEquals(1540, appt0.getStartHour());
      assertEquals(1540, appt0.getStartYear());
      assertFalse(appt0.getValid());
      assertEquals(1540, appt0.getStartMinute());
      assertEquals(1540, appt0.getStartDay());
      assertEquals("tsT8J2xNs", appt0.getTitle());
      assertEquals(1540, appt0.getStartMonth());
  }

  @Test
  public void test03()  throws Throwable  {
      Appt appt0 = new Appt(1, 1, 1, 1, 0, "'?>{w$-|J$o~]^l\"m", "'?>{w$-|J$o~]^l\"m");
      boolean boolean0 = appt0.getValid();
      assertEquals(1, appt0.getStartMinute());
      assertEquals(1, appt0.getStartMonth());
      assertEquals(0, appt0.getStartYear());
      assertEquals(1, appt0.getStartHour());
      assertTrue(boolean0);
      assertEquals("'?>{w$-|J$o~]^l\"m", appt0.getTitle());
      assertEquals("'?>{w$-|J$o~]^l\"m", appt0.getDescription());
      assertEquals(1, appt0.getStartDay());
  }

  @Test
  public void test04()  throws Throwable  {
      Appt appt0 = new Appt(1, 1, 1, 1, 1, "", "");
      int int0 = appt0.getStartYear();
      assertTrue(appt0.getValid());
      assertEquals(1, int0);
      assertEquals(1, appt0.getStartMinute());
      assertEquals(1, appt0.getStartMonth());
      assertEquals(1, appt0.getStartDay());
      assertEquals(1, appt0.getStartHour());
  }

  @Test
  public void test05()  throws Throwable  {
      Appt appt0 = new Appt(0, 0, 0, 0, 0, (String) null, (String) null);
      int int0 = appt0.getStartMonth();
      assertEquals(0, appt0.getStartDay());
      assertFalse(appt0.getValid());
      assertEquals(0, appt0.getStartMinute());
      assertEquals(0, appt0.getStartYear());
      assertEquals(0, int0);
      assertEquals(0, appt0.getStartHour());
  }

  @Test
  public void test06()  throws Throwable  {
      Appt appt0 = new Appt(0, 0, 0, 1, 0, "", " at ");
      int int0 = appt0.getStartMonth();
      assertEquals(" at ", appt0.getDescription());
      assertEquals(0, appt0.getStartDay());
      assertEquals(1, int0);
      assertEquals(0, appt0.getStartMinute());
      assertEquals("", appt0.getTitle());
      assertFalse(appt0.getValid());
      assertEquals(0, appt0.getStartHour());
      assertEquals(0, appt0.getStartYear());
  }

  @Test
  public void test07()  throws Throwable  {
      Appt appt0 = new Appt(11, 11, 11, 11, 11, "E", "E");
      int int0 = appt0.getStartMinute();
      assertEquals(11, appt0.getStartHour());
      assertEquals("E", appt0.getTitle());
      assertEquals(11, appt0.getStartYear());
      assertEquals(11, appt0.getStartMonth());
      assertEquals("E", appt0.getDescription());
      assertEquals(11, appt0.getStartDay());
      assertTrue(appt0.getValid());
      assertEquals(11, int0);
  }

  @Test
  public void test08()  throws Throwable  {
      Appt appt0 = new Appt((-2046), (-2046), 5309, (-2046), 5309, "V3'. w3,WwS2A@!", "V3'. w3,WwS2A@!");
      int int0 = appt0.getStartMinute();
      assertEquals("V3'. w3,WwS2A@!", appt0.getDescription());
      assertEquals((-2046), int0);
      assertEquals(5309, appt0.getStartYear());
      assertEquals(-2046, appt0.getStartMonth());
      assertEquals("V3'. w3,WwS2A@!", appt0.getTitle());
      assertEquals(5309, appt0.getStartDay());
      assertEquals(-2046, appt0.getStartHour());
      assertFalse(appt0.getValid());
  }

  @Test
  public void test09()  throws Throwable  {
      Appt appt0 = new Appt(0, 0, 0, 1, 0, "", " at ");
      int int0 = appt0.getStartHour();
      assertEquals(0, appt0.getStartYear());
      assertEquals(0, appt0.getStartMinute());
      assertEquals(0, int0);
      assertEquals(0, appt0.getStartDay());
      assertEquals(1, appt0.getStartMonth());
      assertEquals(" at ", appt0.getDescription());
      assertFalse(appt0.getValid());
      assertEquals("", appt0.getTitle());
  }

  @Test
  public void test10()  throws Throwable  {
      Appt appt0 = new Appt(299, 299, 299, 201, 299, "X", "9R}e1#!hmt5#>uSkyN&");
      int int0 = appt0.getStartHour();
      assertEquals(201, appt0.getStartMonth());
      assertEquals(299, appt0.getStartYear());
      assertEquals(299, appt0.getStartMinute());
      assertEquals("X", appt0.getTitle());
      assertEquals(299, appt0.getStartDay());
      assertEquals("9R}e1#!hmt5#>uSkyN&", appt0.getDescription());
      assertFalse(appt0.getValid());
      assertEquals(299, int0);
  }

  @Test
  public void test11()  throws Throwable  {
      Appt appt0 = new Appt(598, 0, 0, 598, 0, "jw_-'qn", "jw_-'qn");
      int int0 = appt0.getStartDay();
      assertFalse(appt0.getValid());
      assertEquals(0, int0);
      assertEquals(0, appt0.getStartYear());
      assertEquals("jw_-'qn", appt0.getDescription());
      assertEquals(598, appt0.getStartMonth());
      assertEquals(0, appt0.getStartMinute());
      assertEquals("jw_-'qn", appt0.getTitle());
      assertEquals(598, appt0.getStartHour());
  }

  @Test
  public void test12()  throws Throwable  {
      Appt appt0 = new Appt((-4013), (-4013), (-4013), 0, (-4013), "1$V+2h& %-!\"$F9ixOU", "1$V+2h& %-!\"$F9ixOU");
      int int0 = appt0.getStartDay();
      assertEquals("1$V+2h& %-!\"$F9ixOU", appt0.getDescription());
      assertEquals("1$V+2h& %-!\"$F9ixOU", appt0.getTitle());
      assertEquals((-4013), int0);
      assertEquals(0, appt0.getStartMonth());
      assertEquals(-4013, appt0.getStartYear());
      assertEquals(-4013, appt0.getStartMinute());
      assertFalse(appt0.getValid());
      assertEquals(-4013, appt0.getStartHour());
  }

  @Test
  public void test13()  throws Throwable  {
      Appt appt0 = new Appt(11, 11, 11, 11, 11, "E", "E");
      String string0 = appt0.toString();
      assertNotNull(string0);
      assertEquals("\t11/11/11 at 11:11am ,E, E\n", string0);
  }

  @Test
  public void test14()  throws Throwable  {
      Appt appt0 = new Appt(23, (-1), 23, 23, (-1), "", "");
      assertEquals(23, appt0.getStartDay());
      assertEquals(23, appt0.getStartMonth());
      assertEquals(23, appt0.getStartHour());
      assertEquals(-1, appt0.getStartMinute());
      assertEquals(-1, appt0.getStartYear());
      assertFalse(appt0.getValid());
  }

  @Test
  public void test15()  throws Throwable  {
      Appt appt0 = new Appt(1, 0, 0, 1, 0, ":", "pm");
      int int0 = appt0.getStartYear();
      assertEquals(0, int0);
      assertEquals(":", appt0.getTitle());
      assertEquals("pm", appt0.getDescription());
      assertEquals(1, appt0.getStartMonth());
      assertFalse(appt0.getValid());
      assertEquals(0, appt0.getStartDay());
      assertEquals(1, appt0.getStartHour());
      assertEquals(0, appt0.getStartMinute());
  }

  @Test
  public void test16()  throws Throwable  {
      Appt appt0 = new Appt(12, 12, 12, 12, 12, "Zyv=T\f0h", "Zyv=T\f0h");
      appt0.setStartMinute(284);
      assertEquals(284, appt0.getStartMinute());
  }

  @Test
  public void test17()  throws Throwable  {
      Appt appt0 = new Appt(12, 12, 12, 12, 12, "Zyv=T\f0h", "Zyv=T\f0h");
      String string0 = appt0.toString();
      assertEquals("\t12/12/12 at 12:12pm ,Zyv=T\f0h, Zyv=T\f0h\n", string0);
      assertNotNull(string0);
  }

  @Test
  public void test18()  throws Throwable  {
      Appt appt0 = new Appt(1, 1, 1, 1, 1, "", "");
      String string0 = appt0.toString();
      assertEquals("\t1/1/1 at 1:1am ,, \n", string0);
      assertNotNull(string0);
  }

  @Test
  public void test19()  throws Throwable  {
      Appt appt0 = new Appt(12, 12, 12, 12, 12, "Zyv=T\f0h", "Zyv=T\f0h");
      appt0.setStartYear(12);
      assertEquals(12, appt0.getStartHour());
      assertEquals(12, appt0.getStartMinute());
      assertEquals("Zyv=T\f0h", appt0.getDescription());
      assertEquals(12, appt0.getStartDay());
      assertEquals("Zyv=T\f0h", appt0.getTitle());
      assertEquals(12, appt0.getStartMonth());
      assertTrue(appt0.getValid());
      assertEquals(12, appt0.getStartYear());
  }

  @Test
  public void test20()  throws Throwable  {
      Appt appt0 = new Appt((-1018), (-1018), (-1018), (-1018), (-1018), "7tRc'(sKfh*|4", "");
      appt0.setStartMonth((-1373));
      assertEquals(-1373, appt0.getStartMonth());
  }

  @Test
  public void test21()  throws Throwable  {
      Appt appt0 = new Appt((-4013), (-4013), (-4013), 0, (-4013), "1$V+2h& %-!\"$F9ixOU", "1$V+2h& %-!\"$F9ixOU");
      appt0.setStartHour((-4013));
      assertEquals(0, appt0.getStartMonth());
      assertEquals("1$V+2h& %-!\"$F9ixOU", appt0.getDescription());
      assertEquals(-4013, appt0.getStartYear());
      assertEquals(-4013, appt0.getStartHour());
      assertEquals(-4013, appt0.getStartMinute());
      assertFalse(appt0.getValid());
      assertEquals("1$V+2h& %-!\"$F9ixOU", appt0.getTitle());
      assertEquals(-4013, appt0.getStartDay());
  }

  @Test
  public void test22()  throws Throwable  {
      Appt appt0 = new Appt(12, 12, 12, 12, 12, "Zyv=T\f0h", "Zyv=T\f0h");
      appt0.setStartDay(284);
      assertEquals(284, appt0.getStartDay());
  }

  @Test
  public void test23()  throws Throwable  {
      Appt appt0 = new Appt(0, (-1771), 0, 0, (-1771), (String) null, (String) null);
      appt0.setTitle((String) null);
      assertEquals(0, appt0.getStartDay());
      assertEquals(-1771, appt0.getStartYear());
      assertEquals(-1771, appt0.getStartMinute());
      assertFalse(appt0.getValid());
      assertEquals(0, appt0.getStartHour());
      assertEquals(0, appt0.getStartMonth());
  }

  @Test
  public void test24()  throws Throwable  {
      Appt appt0 = new Appt(0, 0, 738, 0, 738, "*)C+WmFvu//R", "*)C+WmFvu//R");
      String string0 = appt0.toString();
      assertEquals("*)C+WmFvu//R", appt0.getDescription());
      assertNull(string0);
      assertEquals("*)C+WmFvu//R", appt0.getTitle());
      assertEquals(738, appt0.getStartDay());
      assertEquals(0, appt0.getStartMinute());
      assertEquals(0, appt0.getStartHour());
      assertEquals(738, appt0.getStartYear());
      assertEquals(0, appt0.getStartMonth());
  }

  @Test
  public void test25()  throws Throwable  {
      Appt appt0 = new Appt(1, 59, 1, 59, 1, "pm", "pm");
      String string0 = appt0.getTitle();
      assertEquals(1, appt0.getStartHour());
      assertEquals(59, appt0.getStartMinute());
      assertEquals(59, appt0.getStartMonth());
      assertEquals("pm", appt0.getDescription());
      assertEquals("pm", string0);
      assertEquals(1, appt0.getStartDay());
      assertFalse(appt0.getValid());
      assertEquals(1, appt0.getStartYear());
  }

  @Test
  public void test26()  throws Throwable  {
      Appt appt0 = new Appt((-1), (-1), (-1), (-88), (-1), "Q)H", "Q)H");
      int int0 = appt0.getStartYear();
      assertEquals((-1), int0);
      assertEquals("Q)H", appt0.getDescription());
      assertEquals(-88, appt0.getStartMonth());
      assertEquals("Q)H", appt0.getTitle());
      assertEquals(-1, appt0.getStartMinute());
      assertEquals(-1, appt0.getStartDay());
      assertEquals(-1, appt0.getStartHour());
      assertFalse(appt0.getValid());
  }

  @Test
  public void test27()  throws Throwable  {
      Appt appt0 = new Appt((-1018), (-1018), (-1018), (-1018), (-1018), "7tRc'(sKfh*|4", "");
      int int0 = appt0.getStartMonth();
      assertEquals(-1018, appt0.getStartMinute());
      assertEquals(-1018, appt0.getStartYear());
      assertEquals((-1018), int0);
      assertEquals(-1018, appt0.getStartHour());
      assertEquals("", appt0.getDescription());
      assertEquals("7tRc'(sKfh*|4", appt0.getTitle());
      assertFalse(appt0.getValid());
      assertEquals(-1018, appt0.getStartDay());
  }

  @Test
  public void test28()  throws Throwable  {
      Appt appt0 = new Appt(0, 0, 31, (-1), 0, ";l1)*5YtVNdi9?5", "");
      int int0 = appt0.getStartMinute();
      assertEquals(0, appt0.getStartHour());
      assertEquals(0, appt0.getStartYear());
      assertEquals("", appt0.getDescription());
      assertFalse(appt0.getValid());
      assertEquals(";l1)*5YtVNdi9?5", appt0.getTitle());
      assertEquals(0, int0);
      assertEquals(-1, appt0.getStartMonth());
      assertEquals(31, appt0.getStartDay());
  }

  @Test
  public void test29()  throws Throwable  {
      Appt appt0 = new Appt((-1927), (-1927), (-1927), (-1927), (-1927), "w;=", "w;=");
      int int0 = appt0.getStartHour();
      assertEquals("w;=", appt0.getDescription());
      assertFalse(appt0.getValid());
      assertEquals("w;=", appt0.getTitle());
      assertEquals(-1927, appt0.getStartMinute());
      assertEquals(-1927, appt0.getStartMonth());
      assertEquals((-1927), int0);
      assertEquals(-1927, appt0.getStartYear());
      assertEquals(-1927, appt0.getStartDay());
  }

  @Test
  public void test30()  throws Throwable  {
      Appt appt0 = new Appt(1540, 1540, 1540, 1540, 1540, "tsT8J2xNs", "");
      int int0 = appt0.getStartDay();
      assertEquals("", appt0.getDescription());
      assertEquals("tsT8J2xNs", appt0.getTitle());
      assertEquals(1540, int0);
      assertEquals(1540, appt0.getStartMinute());
      assertEquals(1540, appt0.getStartMonth());
      assertFalse(appt0.getValid());
      assertEquals(1540, appt0.getStartHour());
      assertEquals(1540, appt0.getStartYear());
  }

  @Test
  public void test31()  throws Throwable  {
      Appt appt0 = new Appt(1, 1, 1, 1, 1, "", "");
      appt0.getDescription();
      assertEquals(1, appt0.getStartMinute());
      assertEquals(1, appt0.getStartMonth());
      assertEquals(1, appt0.getStartHour());
      assertEquals(1, appt0.getStartYear());
      assertTrue(appt0.getValid());
      assertEquals(1, appt0.getStartDay());
  }

  @Test
  public void test32()  throws Throwable  {
      Appt appt0 = new Appt(1113, 1113, 1113, 2794, 2794, ".KZeN", ".KZeN");
      boolean boolean0 = appt0.getValid();
      assertEquals(2794, appt0.getStartYear());
      assertEquals(1113, appt0.getStartHour());
      assertEquals(1113, appt0.getStartDay());
      assertEquals(1113, appt0.getStartMinute());
      assertFalse(boolean0);
      assertEquals(".KZeN", appt0.getDescription());
      assertEquals(2794, appt0.getStartMonth());
      assertEquals(".KZeN", appt0.getTitle());
  }
}
