/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 18 07:02:10 GMT 2017
 */

package edu.osu.cs362;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import edu.osu.cs362.Unit;
import java.util.NoSuchElementException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Unit_ESTest extends Unit_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Unit unit0 = new Unit();
      unit0.SetAbility("", 0.0, 1443);
      unit0.GetTreasure();
      assertEquals(1444, unit0.GetLevel());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Unit unit0 = new Unit();
      unit0.SetAbility("", 1000.0, 0);
      unit0.Attacking();
      assertEquals(1, unit0.GetLevel());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Unit unit0 = new Unit();
      unit0.SetAbility((String) null, (-3057.977307671), 443);
      int int0 = unit0.GetLevel();
      assertEquals(443, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Unit unit0 = new Unit();
      unit0.SetAbility("jV a(*", 1.0, (-393));
      int int0 = unit0.GetLevel();
      assertEquals((-393), int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Unit unit0 = new Unit();
      int int0 = unit0.GetLevel();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Unit unit0 = new Unit();
      unit0.SetAbility((String) null, 6029.044, 4);
      unit0.GetTreasure();
      unit0.Attacking();
      unit0.Attacking();
      unit0.Attacking();
      unit0.Attacking();
      unit0.GetTreasure();
      // Undeclared exception!
      try { 
        unit0.GetTreasure();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // Cannot level up
         //
         assertThrownBy("edu.osu.cs362.Unit", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Unit unit0 = new Unit();
      // Undeclared exception!
      try { 
        unit0.Attacking();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // Cannot defeaat the monster
         //
         assertThrownBy("edu.osu.cs362.Unit", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Unit unit0 = new Unit();
      unit0.SetAbility("1+Y8/E", 1, 10);
      // Undeclared exception!
      try { 
        unit0.GetTreasure();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // Cannot level up
         //
         assertThrownBy("edu.osu.cs362.Unit", e);
      }
  }
}
